defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}

name: robomimic_can_dsrl_${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
logdir: ${log_dir}/robomimic-dsrl/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ./dppo/log/robomimic-pretrain/can/can_pre_diffusion_mlp_ta4_td20/2024-06-28_13-29-54/checkpoint/state_5000.pt
offline_data_path: ./dppo/data/robomimic/can/train.npz
dppo_path: ./dppo
normalization_path: ./dppo/log/robomimic/${env_name}/normalization.npz

algorithm: fast # options are: dsrl_na, dsrl_sac

seed: 1
device: cuda:0
use_wandb: True
env_name: can
log_dir: ./logs 
obs_dim: 23
action_dim: 7 # this is base action dim!
cond_steps: 1
act_steps: 4 # action chunk size of base policy
load_offline_data: True # if true, load offline demonstration data into replay buffer
deterministic_eval: False # if true, run eval with both deterministic actions, as well as stochastic

total_timesteps: 200000
eval_interval: 300
num_evals: 200
save_model_interval: 10000
save_replay_buffer: False

env:
  n_envs:  4
  n_eval_envs: 25
  name: ${env_name}
  max_episode_steps: 300
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 1 
  reward_offset: 0
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    'object'] # same order of preprocessed observations
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True
  observation_meta:
    robot0_eef_pos: 3
    robot0_eef_quat: 4
    robot0_gripper_qpos: 2
    object: 14

wandb:
  project: fast
  run: ${now:%H-%M-%S}_${name}
  group: robomimic-can

policy:
  type: residual # residual, residual_scale
  action_condition: True # Whether to condition policy on base action.
  shape_rewards: False # Whether to use PBRS from base policy values.
  residual_scale_schedule: 50000 # Schedule for clamping residual actions.
  residual_scale: 0.2 # Max. magnitude to clamp residual predictions.
  # residual_sample_schedule: ... # Frequency of sampling residual actions during training.
  drop_velocity: True # Whether to drop velocity from observation for residual policy + base value.

train:
  tau: 0.005 # Target update rate
  actor_lr: 3e-4
  batch_size: 256
  train_freq: 1 # Update model after this many environment steps
  utd: 20 # Number of gradient steps to take per update
  use_layer_norm: True
  layer_size: 2048 # Layer size for actor and critic
  num_layers: 3 # Number of layers for actor and critic
  discount: 0.95
  ent_coef: -1
  target_ent: 0.0
  init_rollout_steps: 1501 # Number of rollout steps of standard diffusion policy to collect for replay buffer before training starts
  init_rollout_noise_magnitude: 0.1 # Initial noise magnitude for rollout actions
  # action_magnitude: 1.5 # Maximum action magnitude in noise action space
  n_critics: 2 # Number of critic Q networks
  critic_backup_combine_type: min

base:
  tau: 0.005 # Target update rate
  lr: 3e-4
  fqe_steps: 5000
  vd_steps: 5000
  vd_samples: 16
  # lr_scheduler: cosine # Options: constant, linear, cosine
  batch_size: 256
  use_layer_norm: ${train.use_layer_norm}
  layer_size: ${train.layer_size}
  num_layers: ${train.num_layers}
  discount: 0.99
  n_critics: ${train.n_critics}
  critic_backup_combine_type: ${train.critic_backup_combine_type}

model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  ft_denoising_steps: 0
  predict_epsilon: True
  denoised_clip_value: 1.0
  randn_clip_value: 3
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${act_steps}
    action_dim: ${action_dim}
  horizon_steps: ${act_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: 20
  device: ${device}
  use_ddim: True
  ddim_steps: 8
  controllable_noise: True